version: '3.8'

services:
  app-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-service
    ports:
      - "8081:8080"
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: "prod"